version: '3.9'

services:
  kibana:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: kibana-development
    restart: unless-stopped
    ports:
      - '5601:5601'
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - SERVER_NAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - KIBANA_USERNAME=admin
      - KIBANA_PASSWORD=admin
    networks:
      - regenfass

networks:
  regenfass:
    name: regenfass
    driver: bridge
